### ISSUE TITLE
Sample game prototype

### ISSUE THREAD

**Issue by akshaysonvane** [Akshay2005/cmpe202-project#8]
Binary Search game created to assist in project topic selection.

**Comment by rishindrareddy** [comment]
What is this prototype about ? When did we discuss this ?

**Comment by Akshay2005** [comment]
It's a small demo of the binary search game, that we discussed during the meeting. 
And as per the description of the commit, this demo will assist us in selecting the project topic as it visualizes the concept.

**Comment by rishindrareddy** [comment]
There might have been some kind of misunderstanding i guess, team is yet to discuss CS:Unplugged activities and choose the analyze activity according to children's point of view which they will enjoy playing.
In team meeting we did not discuss about checking out any demo games. Team members believes that you are knowingly or unknowingly displaying bulldozing traits, which won't help team progress on any ground. Please think about that and team members are ready to help you in any issue you face. Let's discuss this in next meeting.
Thank you.
