### ISSUE TITLE
Second Team Meeting

### ISSUE THREAD

**Issue by varundrogba** [Akshay2005/cmpe202-project#9]
Finalize the date and time for the next team meeting. Agenda for it would be to finalize topic and outline of our project. We must aim to deliver a problem statement and project charter plan. We must have a meeting before 9/18 which is the deadline for submitting our first team assignment.

**Comment by rishindrareddy** [comment]
I am available all day tomorrow on hangout.

**Comment by varundrogba** [comment]
I am also available today as well as tomorrow, others please confirm time

**Comment by akshaysonvane** [comment]
If everyone's available, let's meet up today after lunch.

**Comment by rishindrareddy** [comment]
Let's meet up and finalize the activity to be developed. I am available all day,will join on hangout.

**Comment by varundrogba** [comment]
I am also available all day

**Comment by MandarGade** [comment]
we will meet tomorrow after class and we will decide the cs-unplugged activity which we are going to implement.

**Comment by rishindrareddy** [comment]
Yes after class we can have a meeting and finalize the activity on which we have to develop a game.

**Comment by SunilKumarGarg** [comment]
Yes, see all of you after class.
